import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Floor Mats',
      slug:'floor_mats',
      category: 'Interior',
      image: '/images/mats.jpg',
      price: 120,
      retailValue:110,
      countInStock: 10,
      brand: 'Nike',
      year: 2011,
      model: 'corolla',
      make: 'Toyota',
      partNumber:2020,
      laborOPCode:4496,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '2',
      name: 'Pedals',
      slug:'pedals',
      category: 'Interior',
      image: '/images/pedals.jpg',
      price: 120,
      retailValue:110,
      countInStock: 10,
      brand: 'Nike',
      year: 2011,
      model: 'corolla',
      make: 'Toyota',
      partNumber:2020,
      laborOPCode:4496,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },{
      // _id: '3',
      name: 'Side Mirrors',
      slug:'side_mirrors',
      category: 'Exterior',
      image: '/images/sidemirror.jpg',
      price: 120,
      retailValue:110,
      countInStock: 10,
      brand: 'Nike',
      year: 2011,
      model: 'corolla',
      make: 'Toyota',
      partNumber:2020,
      laborOPCode:4496,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },{
      // _id: '4',
      name: 'Shifting Knobs',
      slug:'shifting_knobs',
      category: 'Interior',
      image: '/images/knobs.jpg',
      price: 120,
      retailValue:110,
      countInStock: 10,
      brand: 'Nike',
      year: 2011,
      model: 'corolla',
      make: 'Toyota',
      partNumber:2020,
      laborOPCode:4496,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },{
      // _id: '5',
      name: 'Suspension',
      slug:'suspension',
      category: 'Performance',
      image: '/images/suspension.jpg',
      price: 120,
      retailValue:110,
      countInStock: 10,
      brand: 'Nike',
      year: 2011,
      model: 'corolla',
      make: 'Toyota',
      partNumber:2020,
      laborOPCode:4496,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },{
      // _id: '6',
      name: 'Gauges',
      slug:'gauges',
      category: 'Interior',
      image: '/images/gauges.jpg',
      price: 120,
      retailValue:110,
      countInStock: 10,
      brand: 'Nike',
      year: 2011,
      model: 'corolla',
      make: 'Toyota',
      partNumber:2020,
      laborOPCode:4496,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },{
      // _id: '7',
      name: 'Exhaust',
      slug:'exhaust',
      category: 'Perfomance',
      image: '/images/exhaust.jpg',
      price: 120,
      retailValue:110,
      countInStock: 10,
      brand: 'Nike',
      year: 2011,
      model: 'corolla',
      make: 'Toyota',
      partNumber:2020,
      laborOPCode:4496,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },{
      // _id: '8',
      name: 'Spoilers',
      slug:'spoilers',
      category: 'Exterior',
      image: '/images/spoilers.jpg',
      price: 120,
      retailValue:110,
      countInStock: 10,
      brand: 'Nike',
      year: 2011,
      model: 'corolla',
      make: 'Toyota',
      partNumber:2020,
      laborOPCode:4496,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
